package es.uma.informatica.selenium.test;

// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;

public class DefaultSuiteIT {
	private WebDriver driver;
	private Map<String, Object> vars;
	JavascriptExecutor js;

	@Before
	public void setUp() {
		driver = new FirefoxDriver();
		js = (JavascriptExecutor) driver;
		vars = new HashMap<String, Object>();
	}

	@After
	public void tearDown() {
		driver.quit();
	}
	
	@Test
	public void generarNuevaContrasea() {
	    driver.get("http://0.0.0.0:8080/Grupo_L-war/faces/Login.xhtml");
	    driver.manage().window().setSize(new Dimension(826, 694));
	    driver.findElement(By.linkText("¿Has olvidado tu contraseña?")).click();
	    driver.findElement(By.id("j_idt8:email")).click();
	    driver.findElement(By.id("j_idt8:passwd")).sendKeys("123");
	    driver.findElement(By.id("j_idt8:email")).sendKeys("marta@uma.es");
	    driver.findElement(By.id("j_idt8:passwd2")).click();
	    driver.findElement(By.id("j_idt8:passwd2")).sendKeys("123");
	    driver.findElement(By.name("j_idt8:j_idt19")).click();
	    driver.findElement(By.id("j_idt7:user")).click();
	    driver.findElement(By.id("j_idt7:user")).sendKeys("marta@uma.es");
	    driver.findElement(By.id("j_idt7:pass")).sendKeys("123");
	    driver.findElement(By.id("j_idt7:entrar")).click();
	    assertThat(driver.findElement(By.id("nombre")).getText(), is("Hola, Marta."));
	    driver.findElement(By.cssSelector(".titulo")).click();
	    assertThat(driver.findElement(By.cssSelector(".titulo")).getText(), is("PRINCIPAL"));
	    driver.findElement(By.cssSelector("b")).click();
	    assertThat(driver.findElement(By.cssSelector("b")).getText(), is("MIS DATOS"));
	    driver.findElement(By.linkText("Cerrar Sesion")).click();
	}
	@Test
	  public void leerMatriculaA() {
	    driver.get("http://0.0.0.0:8080/Grupo_L-war/faces/Login.xhtml");
	    driver.manage().window().setSize(new Dimension(826, 694));
	    driver.findElement(By.id("j_idt7:user")).click();
	    driver.findElement(By.id("j_idt7:user")).sendKeys("marta@uma.es");
	    driver.findElement(By.id("j_idt7:pass")).sendKeys("123");
	    driver.findElement(By.id("j_idt7:entrar")).click();
	    driver.findElement(By.cssSelector(".inicio")).click();
	    assertThat(driver.findElement(By.id("nombre")).getText(), is("Hola, Marta."));
	    driver.findElement(By.cssSelector(".titulo")).click();
	    assertThat(driver.findElement(By.cssSelector(".titulo")).getText(), is("PRINCIPAL"));
	    driver.findElement(By.id("leerMatricula")).click();
	    driver.findElement(By.cssSelector(".titulo")).click();
	    assertThat(driver.findElement(By.cssSelector(".titulo")).getText(), is("MATRICULA"));
	    driver.findElement(By.id("j_idt25:dtMat:0:j_idt34")).click();
	    assertThat(driver.findElement(By.id("j_idt25:dtMat:0:j_idt34")).getText(), is("105600003"));
	    assertThat(driver.findElement(By.id("j_idt25:dtMat:0:j_idt29")).getText(), is("306000004"));
	    assertThat(driver.findElement(By.id("j_idt25:dtMat:0:j_idt31")).getText(), is("2019-12-29"));
	    driver.findElement(By.linkText("Cerrar Sesion")).click();
	  }
	
	@Test
<<<<<<< HEAD
	  public void leerAsignturaA() {
	    driver.get("http://0.0.0.0:8080/Grupo_L-war/faces/Login.xhtml");
	    driver.manage().window().setSize(new Dimension(826, 694));
=======
	  public void logginSecretaria() {
	    driver.get("http://localhost:8080/Grupo_L-war/faces/Login.xhtml");
	    driver.manage().window().setSize(new Dimension(1158, 655));
	    driver.findElement(By.id("j_idt7:user")).sendKeys("pepe@uma.es");
	    driver.findElement(By.id("j_idt7:pass")).sendKeys("123");
	    driver.findElement(By.id("j_idt7:entrar")).click();
	    assertThat(driver.findElement(By.id("nombre2")).getText(), is("Hola, Jefe."));
	  }
	
	
	@Test
	  public void leerTitulaSec() {
	    driver.get("http://0.0.0.0:8080/Grupo_L-war/");
	    driver.manage().window().setSize(new Dimension(679, 616));
	    driver.findElement(By.id("inicio")).click();
	    driver.findElement(By.id("j_idt7:user")).click();
	    driver.findElement(By.id("j_idt7:pass")).sendKeys("123");
	    driver.findElement(By.id("j_idt7:user")).sendKeys("pepe@uma.es");
	    driver.findElement(By.id("j_idt7:entrar")).click();
	    driver.findElement(By.id("leerTitulacion")).click();
	    assertThat(driver.findElement(By.id("titulacion:dtTitulacion:0:j_idt32")).getText(), is("1041"));
	    assertThat(driver.findElement(By.id("titulacion:dtTitulacion:4:j_idt32")).getText(), is("1073"));
	  }
	
	@Test
	  public void leertituusu() {
	    driver.get("http://0.0.0.0:8080/Grupo_L-war/");
	    driver.manage().window().setSize(new Dimension(679, 616));
	    driver.findElement(By.id("inicio")).click();
	    driver.findElement(By.id("j_idt7:user")).click();
	    driver.findElement(By.id("j_idt7:pass")).sendKeys("123");
	    driver.findElement(By.id("j_idt7:user")).sendKeys("rocio22@uma.es");
	    driver.findElement(By.id("j_idt7:entrar")).click();
	    driver.findElement(By.id("leerTitulacion")).click();
	    assertThat(driver.findElement(By.id("titulacionalum:dtTitulacion:0:j_idt25")).getText(), is("1041"));
	    assertThat(driver.findElement(By.id("titulacionalum:dtTitulacion:1:j_idt25")).getText(), is("1043"));
	  }
	
	@Test
	  public void expedienteAlumno() {
	    driver.get("http://0.0.0.0:8080/Grupo_L-war/");
	    driver.manage().window().setSize(new Dimension(679, 616));
	    driver.findElement(By.id("inicio")).click();
	    driver.findElement(By.id("j_idt7:user")).click();
	    driver.findElement(By.id("j_idt7:pass")).sendKeys("123");
	    driver.findElement(By.id("j_idt7:user")).sendKeys("rocio22@uma.es");
	    driver.findElement(By.id("j_idt7:entrar")).click();
	    driver.findElement(By.id("leerExpediente")).click();
	    {
	      List<WebElement> elements = driver.findElements(By.id("a"));
	      assert(elements.size() > 0);
	    }
	    assertThat(driver.findElement(By.id("expediente:dtExpediente:0:j_idt26")).getText(), is("104195486"));
	    assertThat(driver.findElement(By.id("expediente:dtExpediente:1:j_idt26")).getText(), is("104300002"));
	  }
	 
	 @Test
	  public void leerEncuestaA() {
		driver.get("http://localhost:8080/Grupo_L-war/");
	    driver.manage().window().setSize(new Dimension(977, 715));
	    driver.findElement(By.id("inicio")).click();
>>>>>>> branch 'Facets' of https://github.com/AlvaroM12/GrupoL.git
	    driver.findElement(By.id("j_idt7:user")).click();
	    driver.findElement(By.id("j_idt7:user")).sendKeys("marta@uma.es");
	    driver.findElement(By.id("j_idt7:pass")).click();
	    driver.findElement(By.id("j_idt7:pass")).sendKeys("123");
	    driver.findElement(By.id("j_idt7:entrar")).click();
	    driver.findElement(By.cssSelector(".inicio")).click();
	    assertThat(driver.findElement(By.id("nombre")).getText(), is("Hola, Marta."));
	    driver.findElement(By.cssSelector(".titulo")).click();
	    assertThat(driver.findElement(By.cssSelector(".titulo")).getText(), is("PRINCIPAL"));
	    driver.findElement(By.id("leerAsignaturas")).click();
	    driver.findElement(By.cssSelector(".titulo")).click();
	    assertThat(driver.findElement(By.cssSelector(".titulo")).getText(), is("ASIGNATURAS"));
	    assertThat(driver.findElement(By.id("j_idt25:dtAsig:0:j_idt28")).getText(), is("40660"));
	    driver.findElement(By.id("j_idt25:dtAsig:0:j_idt29")).click();
	    assertThat(driver.findElement(By.id("j_idt25:dtAsig:0:j_idt29")).getText(), is("Grado en Ingenieria de la Salud"));
	    driver.findElement(By.id("j_idt25:dtAsig:0:j_idt30")).click();
	    driver.findElement(By.cssSelector("td:nth-child(3)")).click();
	    assertThat(driver.findElement(By.id("j_idt25:dtAsig:0:j_idt30")).getText(), is("103"));
	    assertThat(driver.findElement(By.id("j_idt25:dtAsig:0:j_idt31")).getText(), is("6"));
	    driver.findElement(By.cssSelector("td:nth-child(5)")).click();
	    assertThat(driver.findElement(By.cssSelector("td:nth-child(5)")).getText(), is("0"));
	    assertThat(driver.findElement(By.id("j_idt25:dtAsig:0:j_idt33")).getText(), is("6"));
	    assertThat(driver.findElement(By.id("j_idt25:dtAsig:0:j_idt34")).getText(), is("Si"));
	    assertThat(driver.findElement(By.id("j_idt25:dtAsig:0:j_idt35")).getText(), is("EDA"));
	    driver.findElement(By.cssSelector("td:nth-child(9)")).click();
	    assertThat(driver.findElement(By.id("j_idt25:dtAsig:0:j_idt36")).getText(), is("3"));
	    assertThat(driver.findElement(By.id("j_idt25:dtAsig:0:j_idt38")).getText(), is("1 Semestre"));
	    driver.findElement(By.cssSelector("td:nth-child(12)")).click();
	    assertThat(driver.findElement(By.id("j_idt25:dtAsig:0:j_idt39")).getText(), is("No"));
	    driver.findElement(By.linkText("Cerrar Sesion")).click();
	  }
	
	@Test
	  public void leerAsignaturaS() {
	    driver.get("http://0.0.0.0:8080/Grupo_L-war/faces/Login.xhtml");
	    driver.manage().window().setSize(new Dimension(887, 631));
	    driver.findElement(By.id("j_idt7:user")).sendKeys("pepe@uma.es");
	    driver.findElement(By.id("j_idt7:pass")).sendKeys("123");
	    driver.findElement(By.id("j_idt7:entrar")).click();
	    driver.findElement(By.cssSelector(".inicio")).click();
	    assertThat(driver.findElement(By.id("nombre2")).getText(), is("Hola, Jefe."));
	    driver.findElement(By.cssSelector(".titulo")).click();
	    assertThat(driver.findElement(By.cssSelector(".titulo")).getText(), is("PRINCIPAL"));
	    driver.findElement(By.id("leerAsignaturas")).click();
	    driver.findElement(By.cssSelector(".titulo")).click();
	    assertThat(driver.findElement(By.cssSelector(".titulo")).getText(), is("ASIGNATURAS"));
	    driver.findElement(By.cssSelector(".ui-widget-content:nth-child(1) > td:nth-child(1)")).click();
	    assertThat(driver.findElement(By.id("j_idt41:dtAsignaturas:0:j_idt43")).getText(), is("40658"));
	    assertThat(driver.findElement(By.id("j_idt41:dtAsignaturas:0:j_idt44")).getText(), is("Grado en Ingenieria del Software"));
	    assertThat(driver.findElement(By.id("j_idt41:dtAsignaturas:1:j_idt43")).getText(), is("40659"));
	    assertThat(driver.findElement(By.id("j_idt41:dtAsignaturas:2:j_idt43")).getText(), is("40660"));
	    driver.findElement(By.cssSelector(".ui-widget-content:nth-child(3) > td:nth-child(2)")).click();
	    assertThat(driver.findElement(By.id("j_idt41:dtAsignaturas:2:j_idt44")).getText(), is("Grado en Ingenieria de la Salud"));
	    driver.findElement(By.cssSelector(".ui-widget-content:nth-child(4) > td:nth-child(1)")).click();
	    assertThat(driver.findElement(By.id("j_idt41:dtAsignaturas:3:j_idt43")).getText(), is("50658"));
	    driver.findElement(By.cssSelector(".ui-widget-content:nth-child(4) > td:nth-child(2)")).click();
	    assertThat(driver.findElement(By.id("j_idt41:dtAsignaturas:3:j_idt44")).getText(), is("Grado en Ingenieria Informatica"));
	    driver.findElement(By.id("j_idt41:dtAsignaturas:4:j_idt43")).click();
	    assertThat(driver.findElement(By.id("j_idt41:dtAsignaturas:4:j_idt43")).getText(), is("50659"));
	    driver.findElement(By.cssSelector(".ui-widget-content:nth-child(5) > td:nth-child(2)")).click();
	    assertThat(driver.findElement(By.id("j_idt41:dtAsignaturas:4:j_idt44")).getText(), is("Grado en Ingenieria Informatica"));
	    driver.findElement(By.cssSelector(".ui-widget-content:nth-child(6) > td:nth-child(1)")).click();
	    assertThat(driver.findElement(By.id("j_idt41:dtAsignaturas:5:j_idt43")).getText(), is("50660"));
	    driver.findElement(By.cssSelector(".ui-widget-content:nth-child(6) > td:nth-child(2)")).click();
	    assertThat(driver.findElement(By.id("j_idt41:dtAsignaturas:5:j_idt44")).getText(), is("Doble Grado en Ingenieria Informatica y Matematicas"));
	    driver.findElement(By.linkText("Cerrar Sesion")).click();
	}
	
	@Test
	  public void leerAlumnoA() {
	    driver.get("http://0.0.0.0:8080/Grupo_L-war/faces/Login.xhtml");
	    driver.manage().window().setSize(new Dimension(826, 694));
	    driver.findElement(By.id("j_idt7:user")).click();
	    driver.findElement(By.id("j_idt7:pass")).sendKeys("123");
	    driver.findElement(By.id("j_idt7:user")).sendKeys("marta@uma.es");
	    driver.findElement(By.id("j_idt7:entrar")).click();
	    driver.findElement(By.cssSelector(".inicio")).click();
	    assertThat(driver.findElement(By.id("nombre")).getText(), is("Hola, Marta."));
	    driver.findElement(By.cssSelector(".titulo")).click();
	    assertThat(driver.findElement(By.cssSelector(".titulo")).getText(), is("PRINCIPAL"));
	    driver.findElement(By.id("leerAlumnos")).click();
	    driver.findElement(By.cssSelector(".titulo")).click();
	    assertThat(driver.findElement(By.cssSelector(".titulo")).getText(), is("ALUMNOS"));
	    driver.findElement(By.cssSelector("td:nth-child(1)")).click();
	    assertThat(driver.findElement(By.id("alumnos:dtAlumno:0:j_idt26")).getText(), is("57400152C"));
	    driver.findElement(By.id("alumnos:dtAlumno:0:j_idt27")).click();
	    assertThat(driver.findElement(By.id("alumnos:dtAlumno:0:j_idt27")).getText(), is("Marta"));
	    driver.findElement(By.cssSelector("td:nth-child(3)")).click();
	    assertThat(driver.findElement(By.id("alumnos:dtAlumno:0:j_idt28")).getText(), is("Lopez"));
	    driver.findElement(By.cssSelector("td:nth-child(4)")).click();
	    assertThat(driver.findElement(By.id("alumnos:dtAlumno:0:j_idt29")).getText(), is("Perez"));
	    driver.findElement(By.cssSelector("td:nth-child(5)")).click();
	    assertThat(driver.findElement(By.id("alumnos:dtAlumno:0:j_idt30")).getText(), is("marta@uma.es"));
	    driver.findElement(By.cssSelector("td:nth-child(6)")).click();
	    assertThat(driver.findElement(By.id("alumnos:dtAlumno:0:j_idt31")).getText(), is("IsidreBlancoZambrano@dayrep.com"));
	    driver.findElement(By.cssSelector("td:nth-child(7)")).click();
	    assertThat(driver.findElement(By.id("alumnos:dtAlumno:0:j_idt32")).getText(), is("760544184"));
	    driver.findElement(By.cssSelector("td:nth-child(8)")).click();
	    assertThat(driver.findElement(By.id("alumnos:dtAlumno:0:j_idt33")).getText(), is("Reisedor 77"));
	    driver.findElement(By.cssSelector("td:nth-child(9)")).click();
	    assertThat(driver.findElement(By.id("alumnos:dtAlumno:0:j_idt34")).getText(), is("Almassera"));
	    driver.findElement(By.cssSelector("td:nth-child(10)")).click();
	    assertThat(driver.findElement(By.id("alumnos:dtAlumno:0:j_idt35")).getText(), is("MALAGA"));
	    driver.findElement(By.cssSelector("td:nth-child(11)")).click();
	    assertThat(driver.findElement(By.id("alumnos:dtAlumno:0:j_idt36")).getText(), is("46132"));
	    driver.findElement(By.linkText("Cerrar Sesion")).click();
	  }
<<<<<<< HEAD
	
	
=======
	  
	  @Test
	  public void testPrincipalAlumno() {
		driver.get("http://localhost:8080/Grupo_L-war/");
	    driver.manage().window().setSize(new Dimension(977, 715));
	    driver.findElement(By.id("inicio")).click();
	    driver.findElement(By.id("j_idt7:user")).click();
	    driver.findElement(By.id("j_idt7:user")).sendKeys("rocio22@uma.es");
	    driver.findElement(By.id("j_idt7:pass")).click();
	    driver.findElement(By.id("j_idt7:pass")).sendKeys("123");
	    driver.findElement(By.id("j_idt7:entrar")).click();
	    assertThat(driver.findElement(By.id("nombre")).getText(), is("Hola, Rocio."));
	    {
	      List<WebElement> elements = driver.findElements(By.id("rellenarEncuesta"));
	      assert(elements.size() > 0);
	    }
	    {
	      List<WebElement> elements = driver.findElements(By.id("solicitarCambioGrupo"));
	      assert(elements.size() > 0);
	    }
	    {
	      List<WebElement> elements = driver.findElements(By.id("caja"));
	      assert(elements.size() > 0);
	    }
	    assertThat(driver.findElement(By.linkText("Cerrar Sesion")).getText(), is("Cerrar Sesion"));
	  }
	  
	  @Test
	  public void testGrupo() {
		driver.get("http://localhost:8080/Grupo_L-war/faces/Login.xhtml");
	    driver.manage().window().setSize(new Dimension(1158, 655));
	    driver.findElement(By.id("j_idt7:user")).sendKeys("pepe@uma.es");
	    driver.findElement(By.id("j_idt7:pass")).sendKeys("123");
	    driver.findElement(By.id("j_idt7:entrar")).click();
	    assertThat(driver.findElement(By.id("nombre2")).getText(), is("Hola, Jefe."));
	    driver.findElement(By.id("leerGrupo")).click();
	    {
	      List<WebElement> elements = driver.findElements(By.id("tabla"));
	      assert(elements.size() > 0);
	    }
	    assertThat(driver.findElement(By.id("tabla:dtGrupos:0:j_idt21")).getText(), is("1"));
	    assertThat(driver.findElement(By.id("tabla:dtGrupos:6:j_idt21")).getText(), is("7"));
	    {
	      List<WebElement> elements = driver.findElements(By.id("tabla:crear"));
	      assert(elements.size() > 0);
	    }
	    driver.findElement(By.id("tabla:crear")).click();
	    driver.findElement(By.id("j_idt19:asignar")).click();
	    driver.findElement(By.id("j_idt19:asignar")).sendKeys("150");
	    driver.findElement(By.id("j_idt19:curso")).click();
	    driver.findElement(By.id("j_idt19:curso")).sendKeys("4");
	    driver.findElement(By.id("j_idt19:letra")).click();
	    driver.findElement(By.id("j_idt19:letra")).sendKeys("B");
	    driver.findElement(By.id("j_idt19:turno")).click();
	    driver.findElement(By.id("j_idt19:turno")).sendKeys("MANIANA");
	    driver.findElement(By.id("j_idt19:ingles")).click();
	    driver.findElement(By.id("j_idt19:ingles")).sendKeys("SI");
	    driver.findElement(By.cssSelector("table")).click();
	    driver.findElement(By.id("j_idt19:plazas")).click();
	    driver.findElement(By.id("j_idt19:plazas")).sendKeys("90");
	    driver.findElement(By.id("j_idt19:visible")).click();
	    driver.findElement(By.id("j_idt19:visible")).sendKeys("90");
	    driver.findElement(By.id("j_idt19:titulacion")).click();
	    {
	      WebElement dropdown = driver.findElement(By.id("j_idt19:titulacion"));
	      dropdown.findElement(By.xpath("//option[. = 'Grado en Ingenieria del Software']")).click();
	    }
	    driver.findElement(By.cssSelector("option:nth-child(2)")).click();
	    driver.findElement(By.id("j_idt19:crear")).click();
	    driver.findElement(By.cssSelector(".ui-widget-content:nth-child(8) > td:nth-child(1)")).click();
	    assertThat(driver.findElement(By.id("tabla:dtGrupos:7:j_idt21")).getText(), is("8"));
	    driver.findElement(By.id("tabla:dtGrupos:7:j_idt22")).click();
	    assertThat(driver.findElement(By.id("tabla:dtGrupos:7:j_idt22")).getText(), is("4"));
	    assertThat(driver.findElement(By.id("tabla:dtGrupos:7:j_idt23")).getText(), is("B"));
	    {
	      List<WebElement> elements = driver.findElements(By.id("tabla:dtGrupos:7:eliminar"));
	      assert(elements.size() > 0);
	    }
	    driver.findElement(By.id("tabla:dtGrupos:7:eliminar")).click();
	    driver.findElement(By.cssSelector(".ui-widget-content:nth-child(7) > td:nth-child(1)")).click();
	    {
	      List<WebElement> elements = driver.findElements(By.id("tabla:dtGrupos:7:j_idt21"));
	      assert(elements.size() == 0);
	    }
	    {
	      List<WebElement> elements = driver.findElements(By.id("tabla:dtGrupos:6:modificar"));
	      assert(elements.size() > 0);
	    }
	    driver.findElement(By.id("tabla:dtGrupos:6:modificar")).click();
	    driver.findElement(By.id("j_idt19:plazas")).click();
	    driver.findElement(By.id("j_idt19:plazas")).clear();
	    driver.findElement(By.id("j_idt19:plazas")).sendKeys("180");
	    driver.findElement(By.id("j_idt19:modificar")).click();
	    driver.findElement(By.cssSelector(".ui-widget-content:nth-child(7) > td:nth-child(8)")).click();
	    assertThat(driver.findElement(By.id("tabla:dtGrupos:6:j_idt28")).getText(), is("180"));
	  }
	  
	  @Test
	  public void testCentro() {
		  driver.get("http://localhost:8080/Grupo_L-war/faces/Login.xhtml");
	    driver.manage().window().setSize(new Dimension(1158, 655));
	    driver.findElement(By.id("j_idt7:user")).sendKeys("pepe@uma.es");
	    driver.findElement(By.id("j_idt7:pass")).sendKeys("123");
	    driver.findElement(By.id("j_idt7:entrar")).click();
	    assertThat(driver.findElement(By.id("nombre2")).getText(), is("Hola, Jefe."));
	    driver.findElement(By.id("leerCentro")).click();
	    assertThat(driver.findElement(By.id("centro:dtCentro:0:j_idt21")).getText(), is("1"));
	    assertThat(driver.findElement(By.id("centro:dtCentro:0:j_idt22")).getText(), is("E.T.S Ingenieria Informatica"));
	    assertThat(driver.findElement(By.id("centro:dtCentro:1:j_idt21")).getText(), is("2"));
	    assertThat(driver.findElement(By.id("centro:dtCentro:1:j_idt22")).getText(), is("Escuela de Ingenierias Industriales"));
	    {
	      List<WebElement> elements = driver.findElements(By.id("centro"));
	    }
	  }
	  
	  @Test
	  public void testAsigMatS() {
		driver.get("http://localhost:8080/Grupo_L-war/faces/Login.xhtml");
	    driver.manage().window().setSize(new Dimension(1158, 655));
	    driver.findElement(By.id("j_idt7:user")).sendKeys("pepe@uma.es");
	    driver.findElement(By.id("j_idt7:pass")).sendKeys("123");
	    driver.findElement(By.id("j_idt7:entrar")).click();
	    assertThat(driver.findElement(By.id("nombre2")).getText(), is("Hola, Jefe."));
	    driver.findElement(By.id("leerAsigMa")).click();
	    {
	      List<WebElement> elements = driver.findElements(By.id("asigm"));
	      assert(elements.size() > 0);
	    }
	    assertThat(driver.findElement(By.id("asigm:dtAsigM:0:j_idt35")).getText(), is("306000002"));
	    assertThat(driver.findElement(By.id("asigm:dtAsigM:1:j_idt35")).getText(), is("306000005"));
	    assertThat(driver.findElement(By.id("asigm:dtAsigM:2:j_idt35")).getText(), is("306000001"));
	    assertThat(driver.findElement(By.id("asigm:dtAsigM:3:j_idt35")).getText(), is("306000003"));
	    assertThat(driver.findElement(By.id("asigm:dtAsigM:4:j_idt35")).getText(), is("306000004"));
	    assertThat(driver.findElement(By.id("asigm:dtAsigM:5:j_idt35")).getText(), is("306000006"));
	    driver.findElement(By.id("asigm:dtAsigM:matricula:filter")).click();
	    driver.findElement(By.id("asigm:dtAsigM:matricula:filter")).sendKeys("306000005");
	    driver.findElement(By.id("asigm:dtAsigM:matricula:filter")).sendKeys(Keys.ENTER);
	  }
>>>>>>> branch 'Facets' of https://github.com/AlvaroM12/GrupoL.git

}
