package es.uma.informatica.selenium.test;

// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;

public class DefaultSuiteIT {
	private WebDriver driver;
	private Map<String, Object> vars;
	JavascriptExecutor js;

	@Before
	public void setUp() {
		driver = new FirefoxDriver();
		js = (JavascriptExecutor) driver;
		vars = new HashMap<String, Object>();
	}

	@After
	public void tearDown() {
		driver.quit();
	}
	
	@Test
	  public void inicioSesion() {
		driver.get("http://localhost:8080/Grupo_L-war/");
	    driver.manage().window().setSize(new Dimension(977, 715));
	    driver.findElement(By.id("inicio")).click();
	    driver.findElement(By.id("j_idt7:user")).click();
	    driver.findElement(By.id("j_idt7:user")).sendKeys("rocio22@uma.es");
	    driver.findElement(By.id("j_idt7:pass")).click();
	    driver.findElement(By.id("j_idt7:pass")).sendKeys("123");
	    driver.findElement(By.id("j_idt7:entrar")).click();
	    assertThat(driver.findElement(By.id("nombre")).getText(), is("Hola, Rocio."));
	  }
	
	@Test
	  public void logginSecretaria() {
	    driver.get("http://localhost:8080/Grupo_L-war/faces/Login.xhtml");
	    driver.manage().window().setSize(new Dimension(1158, 655));
	    driver.findElement(By.id("j_idt7:user")).sendKeys("pepe@uma.es");
	    driver.findElement(By.id("j_idt7:pass")).sendKeys("123");
	    driver.findElement(By.id("j_idt7:entrar")).click();
	    assertThat(driver.findElement(By.id("nombre2")).getText(), is("Hola, Jefe."));
	  }
	
	
	 @Test
	  public void leerTitu() {
			driver.get("http://localhost:8080/Grupo_L-war/");
		    driver.manage().window().setSize(new Dimension(977, 715));
		    driver.findElement(By.id("inicio")).click();
		    driver.findElement(By.id("j_idt7:user")).click();
		    driver.findElement(By.id("j_idt7:user")).sendKeys("rocio22@uma.es");
		    driver.findElement(By.id("j_idt7:pass")).click();
		    driver.findElement(By.id("j_idt7:pass")).sendKeys("123");
		    driver.findElement(By.id("j_idt7:entrar")).click();
		    assertThat(driver.findElement(By.id("nombre")).getText(), is("Hola, Rocio."));
		    
	  }
	 
	 @Test
	  public void leerEncuestaA() {
		driver.get("http://localhost:8080/Grupo_L-war/");
	    driver.manage().window().setSize(new Dimension(977, 715));
	    driver.findElement(By.id("inicio")).click();
	    driver.findElement(By.id("j_idt7:user")).click();
	    driver.findElement(By.id("j_idt7:user")).sendKeys("rocio22@uma.es");
	    driver.findElement(By.id("j_idt7:pass")).click();
	    driver.findElement(By.id("j_idt7:pass")).sendKeys("123");
	    driver.findElement(By.id("j_idt7:entrar")).click();
	    assertThat(driver.findElement(By.id("nombre")).getText(), is("Hola, Rocio."));
	    driver.findElement(By.id("leerEncuesta")).click();
	    assertThat(driver.findElement(By.id("encuesta:dtEncuesta:0:j_idt27")).getText(), is("104195486"));
	  }
	 
	  @Test
	  public void leerEncuestaS() {
	    driver.get("http://localhost:8080/Grupo_L-war/faces/Login.xhtml");
	    driver.manage().window().setSize(new Dimension(1158, 655));
	    driver.findElement(By.id("j_idt7:user")).sendKeys("pepe@uma.es");
	    driver.findElement(By.id("j_idt7:pass")).sendKeys("123");
	    driver.findElement(By.id("j_idt7:entrar")).click();
	    assertThat(driver.findElement(By.id("nombre2")).getText(), is("Hola, Jefe."));
	    driver.findElement(By.id("leerEncuesta")).click();
	    assertThat(driver.findElement(By.id("encuestaAlum:dtEncuesta:0:j_idt37")).getText(), is("104100002"));
	    assertThat(driver.findElement(By.id("encuestaAlum:dtEncuesta:0:j_idt39")).getText(), is("2021-06-08 05:54:59.0"));
	    assertThat(driver.findElement(By.id("encuestaAlum:dtEncuesta:1:j_idt37")).getText(), is("104195486"));
	    assertThat(driver.findElement(By.id("encuestaAlum:dtEncuesta:1:j_idt39")).getText(), is("2020-06-08 05:55:07.0"));	    
	  }
	

}
